### ISSUE TITLE
Open Hyper Link crashes when no web browser is installed

### ISSUE THREAD

**Issue by ClemensInBerlin** [whistyun/MdXaml#68]
MdXaml.LinkActions.OpenCommand.Execute crashes on a Windows that has no Web Browser installed.

System.ComponentModel.Win32Exception: An error occurred trying to start process 'https://atlasti.com/de/atlas-ti-legal-center/datenschutzerklaerung-atlas-ti' with working directory 'C:\Program Files\Scientific Software\ATLASti.23'. Der angegebenen Datei ist keine Anwendung zugeordnet.
  at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
  at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
  at MdXaml.LinkActions.OpenCommand.Execute(Object parameter)

**Comment by whistyun** [comment]
MdXaml 1.21.0 has be released.
`ClickAction.SafetyOpenBrowser` is added.
It is show error dialog when the URL fails to open.
Dialog messages are created from exception messages.
